"""Second execution backend lane (path-B). Ledger remains collab; Hermes is not the source of truth."""
from __future__ import annotations

from execution_backend.base import (
    BackendCapability,
    BackendError,
    BackendStatus,
    ExecutionBackend,
    ExecutionBackendABC,
    unsupported,
)
from execution_backend.closed_loop import (
    REVIEW_STUB_ENV,
    artifact_review,
    decision_fn_from_env,
    local_rules_artifact_review,
    make_decision_channel_fail,
    make_fail_once_then_pass,
    run_inprocess_closed_loop,
)
from execution_backend.inprocess_v1 import InProcessExecutionBackend, run_file_job_via_public_api
from execution_backend.run_job_wire import (
    ENV_NAME as COLLAB_EXECUTION_BACKEND_ENV,
    KIND_INPROCESS,
    KIND_TELEAGENT,
    resolve_run_job_backend,
    run_inprocess_charter,
)
from execution_backend.two_job_isolation import (
    ARTIFACT_A as ISO_ARTIFACT_A,
    ARTIFACT_B as ISO_ARTIFACT_B,
    ISO_A_CHARTER,
    ISO_B_CHARTER,
    IsolationError,
    allocate_isolated_workdirs,
    check_workdir_isolation,
    isolation_report,
    prove_shared_workdir_is_not_isolation,
    prove_shared_workspace_collides,
    require_distinct_workdirs,
    run_one_inprocess_job,
    run_two_jobs_claimed,
    run_two_jobs_isolated,
)
from execution_backend.goal_budget import (
    BUDGET_DIRNAME,
    BudgetCost,
    BudgetLimits,
    GoalBudget,
    GoalBudgetError,
    Reservation,
    attach_goal_budget,
    budget_exhausted_result,
    can_enter_running,
    estimate_dispatch_cost,
    limits_from_charter,
    open_goal_budget,
    queued_for_deps_result,
    reset_goal_budget_cache,
    run_dependent_inprocess_jobs,
    simulate_scheduler_goal_deps,
    stable_budget_goal_id,
)
from execution_backend.workdir_claim import (
    ClaimOutcome,
    Occupancy,
    WorkdirClaimError,
    WorkdirClaimRegistry,
    claim_workdir,
    default_registry,
    occupancy_path,
    prove_same_workdir_no_silent_overwrite,
    release_workdir,
    reset_default_registry,
    run_claimed_inprocess_job,
    run_two_jobs_with_claims,
    simulate_scheduler_workdir_claims,
    start_run_with_workdir_claim,
)

__all__ = [
    "BackendCapability",
    "BackendError",
    "BackendStatus",
    "ExecutionBackend",
    "ExecutionBackendABC",
    "InProcessExecutionBackend",
    "unsupported",
    "run_file_job_via_public_api",
    "get_execution_backend",
    "COLLAB_EXECUTION_BACKEND_ENV",
    "KIND_INPROCESS",
    "KIND_TELEAGENT",
    "resolve_run_job_backend",
    "run_inprocess_charter",
    "REVIEW_STUB_ENV",
    "artifact_review",
    "decision_fn_from_env",
    "local_rules_artifact_review",
    "make_decision_channel_fail",
    "make_fail_once_then_pass",
    "run_inprocess_closed_loop",
    "ISO_A_CHARTER",
    "ISO_B_CHARTER",
    "ISO_ARTIFACT_A",
    "ISO_ARTIFACT_B",
    "IsolationError",
    "allocate_isolated_workdirs",
    "check_workdir_isolation",
    "isolation_report",
    "prove_shared_workdir_is_not_isolation",
    "prove_shared_workspace_collides",
    "require_distinct_workdirs",
    "run_one_inprocess_job",
    "run_two_jobs_claimed",
    "run_two_jobs_isolated",
    "ClaimOutcome",
    "Occupancy",
    "WorkdirClaimError",
    "WorkdirClaimRegistry",
    "claim_workdir",
    "default_registry",
    "occupancy_path",
    "prove_same_workdir_no_silent_overwrite",
    "release_workdir",
    "reset_default_registry",
    "run_claimed_inprocess_job",
    "run_two_jobs_with_claims",
    "simulate_scheduler_workdir_claims",
    "start_run_with_workdir_claim",
    "BUDGET_DIRNAME",
    "BudgetCost",
    "BudgetLimits",
    "GoalBudget",
    "GoalBudgetError",
    "Reservation",
    "attach_goal_budget",
    "budget_exhausted_result",
    "can_enter_running",
    "estimate_dispatch_cost",
    "limits_from_charter",
    "open_goal_budget",
    "queued_for_deps_result",
    "reset_goal_budget_cache",
    "run_dependent_inprocess_jobs",
    "simulate_scheduler_goal_deps",
    "stable_budget_goal_id",
]


def get_execution_backend(name: str | None = None, **kwargs):
    """Factory. Default inprocess.local_v1. Hermes not offered here."""
    key = (name or "inprocess").strip().lower()
    if key in ("inprocess", "inprocess.local_v1", "in_process", "local"):
        return InProcessExecutionBackend(**kwargs)
    raise BackendError(BackendStatus.UNSUPPORTED, f"unknown execution backend={name!r}", capability="get_execution_backend")
